(in-package :authdog)

(defclass meta ()
  ((code :initarg :code :reader meta-code)
   (message :initarg :message :reader meta-message))
  (:documentation "Metadata in the response"))

(defclass session ()
  ((remaining-seconds :initarg :remaining-seconds :reader session-remaining-seconds))
  (:documentation "Session information"))

(defclass names ()
  ((id :initarg :id :reader names-id)
   (formatted :initarg :formatted :reader names-formatted)
   (family-name :initarg :family-name :reader names-family-name)
   (given-name :initarg :given-name :reader names-given-name)
   (middle-name :initarg :middle-name :reader names-middle-name)
   (honorific-prefix :initarg :honorific-prefix :reader names-honorific-prefix)
   (honorific-suffix :initarg :honorific-suffix :reader names-honorific-suffix))
  (:documentation "User name information"))

(defclass photo ()
  ((id :initarg :id :reader photo-id)
   (value :initarg :value :reader photo-value)
   (type :initarg :type :reader photo-type))
  (:documentation "User photo"))

(defclass email ()
  ((id :initarg :id :reader email-id)
   (value :initarg :value :reader email-value)
   (type :initarg :type :reader email-type))
  (:documentation "User email"))

(defclass verification ()
  ((id :initarg :id :reader verification-id)
   (email :initarg :email :reader verification-email)
   (verified :initarg :verified :reader verification-verified)
   (created-at :initarg :created-at :reader verification-created-at)
   (updated-at :initarg :updated-at :reader verification-updated-at))
  (:documentation "Email verification status"))

(defclass user ()
  ((id :initarg :id :reader user-id)
   (external-id :initarg :external-id :reader user-external-id)
   (user-name :initarg :user-name :reader user-user-name)
   (display-name :initarg :display-name :reader user-display-name)
   (nick-name :initarg :nick-name :reader user-nick-name)
   (profile-url :initarg :profile-url :reader user-profile-url)
   (title :initarg :title :reader user-title)
   (user-type :initarg :user-type :reader user-user-type)
   (preferred-language :initarg :preferred-language :reader user-preferred-language)
   (locale :initarg :locale :reader user-locale)
   (timezone :initarg :timezone :reader user-timezone)
   (active :initarg :active :reader user-active)
   (names :initarg :names :reader user-names)
   (photos :initarg :photos :reader user-photos)
   (phone-numbers :initarg :phone-numbers :reader user-phone-numbers)
   (addresses :initarg :addresses :reader user-addresses)
   (emails :initarg :emails :reader user-emails)
   (verifications :initarg :verifications :reader user-verifications)
   (provider :initarg :provider :reader user-provider)
   (created-at :initarg :created-at :reader user-created-at)
   (updated-at :initarg :updated-at :reader user-updated-at)
   (environment-id :initarg :environment-id :reader user-environment-id))
  (:documentation "User information"))

(defclass user-info-response ()
  ((meta :initarg :meta :reader user-info-response-meta)
   (session :initarg :session :reader user-info-response-session)
   (user :initarg :user :reader user-info-response-user))
  (:documentation "Response from the /v1/userinfo endpoint"))
