projects:
  python: 'python'
  node: 'node'
  go: 'go'
  rust: 'rust'
  java: 'java'
  csharp: 'csharp'

vcs:
  client: 'git'
  provider: 'github'
  defaultBranch: 'main'

pipeline:
  cacheLifetime: '7 days'
  logRunningCommand: true

telemetry: false
