run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - misspell
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gomnd
  max-issues-per-linter: 0
  max-same-issues: 0
