name: Clojure Tests

on:
  push:
    paths:
      - 'clojure/**'
      - '.github/workflows/clojure-test.yml'
  pull_request:
    paths:
      - 'clojure/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']

    defaults:
      run:
        working-directory: clojure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Install Leiningen
        run: |
          curl -L -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/
          lein version

      - name: Run tests
        run: lein test

      - name: Run static analysis
        run: lein check
