name: PowerShell SDK

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'sdk/powershell/**'
  # pull_request:
  #   paths:
  #     - 'sdk/powershell/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester tests
        shell: pwsh
        working-directory: powershell
        run: |
          # Install Pester if not already available
          if (-not (Get-Module -ListAvailable -Name Pester)) {
            Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
          }
          # Create Pester configuration for v5+
          $Configuration = New-PesterConfiguration
          $Configuration.Run.Path = './Tests'
          $Configuration.Output.Verbosity = 'Detailed'
          $Configuration.Output.OutputFormat = 'NUnitXml'
          $Configuration.Output.OutputPath = 'test-results.xml'
          # Run tests with the configuration
          Invoke-Pester -Configuration $Configuration
