name: R SDK Tests

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS, e.g. macos-latest, windows-latest, ubuntu-latest'
        required: true
        default: 'ubuntu-latest'
        type: string
      r_version:
        description: 'R versions (comma separated)'
        required: true
        default: 'release,devel'
        type: string

permissions: read-all

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      rversions: ${{ steps.setup-matrix.outputs.rversions }}

    steps:
    - name: Set up build matrix
      id: setup-matrix
      run: |
        rversions=$(echo -n '["'; echo -n '${{ github.event.inputs.r_version }}' | sed 's/,/","/g'; echo '"]')
        echo "rversions=$rversions" >> $GITHUB_OUTPUT

  test:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        r: ${{ fromJson(needs.setup-matrix.outputs.rversions) }}
    runs-on: ${{ github.event.inputs.os }}
    name: ${{ github.event.inputs.os }} (${{ matrix.r }})

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up R ${{ matrix.r }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r }}

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: devtools, testthat, httr, jsonlite, R6
        working-directory: r

    - name: Install package dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: r

    - name: Run tests
      run: |
        cd r
        Rscript -e "devtools::test()"

