name: Scala Tests

on:
  push:
    paths:
      - 'scala/**'
      - '.github/workflows/scala-test.yml'
  pull_request:
    paths:
      - 'scala/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.13.12']
        java: ['17', '21']

    defaults:
      run:
        working-directory: scala

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup SBT
        uses: olafurpg/setup-sbt@v3
        with:
          version: 1.9.7

      - name: Cache SBT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            project/target
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run tests
        run: sbt test

      - name: Run scalastyle
        run: sbt scalastyle

      - name: Compile sources
        run: sbt compile

      - name: Compile tests
        run: sbt test:compile
