name: Swift Tests

on:
  push:
    paths:
      - 'swift/**'
      - '.github/workflows/swift-test.yml'
  pull_request:
    paths:
      - 'swift/**'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd swift
          swift build

      - name: Run tests
        run: |
          cd swift
          swift test
