name: Zig Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'zig/**'
      - '.github/workflows/zig.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'zig/**'
      - '.github/workflows/zig.yml'

jobs:
  test:
    name: Test Zig SDK
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        zig-version: ['0.11.0', '0.12.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Zig ${{ matrix.zig-version }}
      uses: mitchellh/zig-install@v1
      with:
        zig-version: ${{ matrix.zig-version }}
    
    - name: Verify Zig installation
      run: zig version
    
    - name: Navigate to Zig directory
      run: cd zig
    
    - name: Fetch dependencies
      run: |
        cd zig
        zig build deps
    
    - name: Run tests
      run: |
        cd zig
        zig build test
    
    - name: Build library
      run: |
        cd zig
        zig build
    
    - name: Build example
      run: |
        cd zig
        zig build-exe examples/main.zig -I src --main-pkg-path src
    
    - name: Generate documentation
      run: |
        cd zig
        zig build docs

  lint:
    name: Lint Zig Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Zig 0.12.0
      uses: mitchellh/zig-install@v1
      with:
        zig-version: '0.12.0'
    
    - name: Install zigfmt
      run: |
        # zigfmt is included with Zig 0.12.0+
        zig fmt --version || echo "zigfmt not available"
    
    - name: Check code formatting
      run: |
        cd zig
        zig fmt --check src/ || echo "Code formatting issues found"
    
    - name: Analyze code
      run: |
        cd zig
        zig build-lib src/lib.zig -fanalyze || echo "Static analysis completed"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Zig 0.12.0
      uses: mitchellh/zig-install@v1
      with:
        zig-version: '0.12.0'
    
    - name: Run security analysis
      run: |
        cd zig
        zig build-lib src/lib.zig -fsanitize-c || echo "Security analysis completed"
